# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 17:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='name',
            new_name='itemname',
        ),
    ]
